import turtle as t
num = eval(input("请输入边长："))
x = eval(input("请输入起始点坐标：x = "))
y = eval(input("请输入起始点坐标：y = "))

t.showturtle()
t.penup()
t.goto(x, y)
t.pendown()
t.forward(num)
t.left(60)
t.forward(num)
t.left(120)
t.forward(num)
t.left(60)
t.forward(num)
t.goto(x, num + y)
t.goto(num + x, num + y)
t.left(180)
t.forward(num)
t.left(120); t.forward(num)
t.left(60); t.forward(num); t.left(120)
t.penup()
t.goto(num + x, num + y)
t.pendown()
t.goto(num + x, y)
t.penup()
t.left(60)
t.forward(num)
t.left(30)
t.pendown()
t.forward(num)
t.left(90)
t.forward(num)
t.left(90)
t.forward(num)
t.goto(x, y)

t.done()